### ISSUE TITLE
Unable to report to influxdb in 0.9.6

### ISSUE THREAD

**Issue by vamsu** [davidB/metrics-influxdb#31]
Here is the exception.. looks like "series" api deprecated.
Instead of using http api, why not use https://github.com/influxdata/influxdb-java driver?

2016-01-07 19:41:15.827 [metrics-influxdb-reporter-thread-1] WARN  metrics_influxdb.InfluxdbReporter [298] - Unable to report to InfluxDB. Discarding data.
java.io.IOException: Server returned HTTP response code: 404for URL: http://localhost:8086/db/rqsmetrics/series?u=rqsuser&p=rqsuser&time_precision=s with content :'Not Found'
	at metrics_influxdb.InfluxdbHttp.sendRequest(InfluxdbHttp.java:152) ~[metrics-influxdb-0.7.0.jar:na]
	at metrics_influxdb.InfluxdbReporter.report(InfluxdbReporter.java:295) ~[metrics-influxdb-0.7.0.jar:na]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116) [metrics-core-3.0.2.jar:3.0.2]

**Comment by davidB** [comment]
Hi,
Support for influxdb 0.9.x is part of the SNAPSHOT version (see README for setup).

We don't use influxdb-java because : 
* to be lightweight
  * on dependencies : metrics-core is the only dependency and it's optional.
  * on runtime overhead (memory, gc)
  * only need to send DATA, no need for the full api
  * on code : simple to understand, to customize (no layer over layer), to improve (debug, optimize)
* it didn't exist when the project was first release (metrics-influxdb is the first java driver to send data to influxdb)

**Comment by vamsu** [comment]
Thanks for the reply. I am still not clear as the master branch InfluxdbHttp.java still calls "series" endpoint. Do you mean I should use HttpInlinerSender.java? as that is only place I see it is calling the /write api.

**Comment by wakandan** [comment]
I have this same problem
