### ISSUE TITLE
Support for 0.12.

### ISSUE THREAD

**Issue by woidda** [davidB/metrics-influxdb#45]
I get `couldn't sent metrics to http://[my servername omitted]:8086, reason: Server returned HTTP response code: 500 for URL: http://[my servername omitted]:8086/write?precision=ms&db=service`
when I am trying to use the library (version 0.8.2) against influxdb 0.12. I hope this is not a local issue for our setup. The server seems to work as telegraf is reporting its metrics correctly.

Unfurtunatly, I have no time to investigate this further right now...

btw @davidB thanks for your efforts

**Comment by seregasheypak** [comment]
Hm... I get `Read timed out`, but I do see measurements in influxDb...
```
2016-05-03 01:19:22.407 m.m.HttpInlinerSender [WARN] couldn't sent metrics to http://influx.com:8086, reason: Read timed out
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_45]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_45]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[?:1.8.0_45]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_45]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_45]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[?:1.8.0_45]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[?:1.8.0_45]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[?:1.8.0_45]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[?:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1535) ~[?:1.8.0_45]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440) ~[?:1.8.0_45]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_45]
	at metrics_influxdb.measurements.HttpInlinerSender.doSend(HttpInlinerSender.java:71) [stormjar.jar:?]
	at metrics_influxdb.measurements.QueueableSender.flush(QueueableSender.java:19) [stormjar.jar:?]
	at metrics_influxdb.measurements.MeasurementReporter.report(MeasurementReporter.java:65) [stormjar.jar:?]
	at com.codahale.metrics.ScheduledReporter.report(ScheduledReporter.java:116) [stormjar.jar:?]
	at com.codahale.metrics.ScheduledReporter$1.run(ScheduledReporter.java:87) [stormjar.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_45]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

```

**Comment by thunderstumpges** [comment]
We are having the same issue. However we are using Influx DB 0.9, and metrics-influxdb 0.8.2. Any fix on this? It is not super high priority, but it is quite annoying having those filling up the log file. I don't want to silence all errors either.

**Comment by davidB** [comment]
The 2 first comment doesn't have same error message.
Without more details about context or suggestion (circuit breaker, retry) or a PR I can't do more (I'm no longer use Influxdb).
